### ISSUE TITLE
format of the .scp file

### ISSUE THREAD

**Issue by dongxinglei** [funcwj/uPIT-for-speech-separation#1]
Hello, what is the format of the .scp file? Similar to \data\2speakers\wav8k\min\tr\s1\011a0101_0.061105_401c020r_-0.061105.wav?

**Comment by funcwj** [comment]
Same format as kaldi's scripts: `<key> <path>`, here is a example:
`sw02001-A /export/corpora3/LDC/LDC97S62/swb1/sw02001.wav`

**Comment by dongxinglei** [comment]
> Same format as kaldi's scripts: `<key> <path>`, here is a example:
> `sw02001-A /export/corpora3/LDC/LDC97S62/swb1/sw02001.wav`

**Comment by dongxinglei** [comment]
> Same format as kaldi's scripts: `<key> <path>`, here is a example:
> `sw02001-A /export/corpora3/LDC/LDC97S62/swb1/sw02001.wav`

I do not know the kaldi format, how to prepare cmvn.dict? Is it convenient to leave WeChat communication?my WeChat is dongxinglei_
