### ISSUE TITLE
.scp文件结构是什么呢，和mix_2_spk_cv相似吗

### ISSUE THREAD

**Issue by lvyilan23** [funcwj/uPIT-for-speech-separation#2]
我用给出的create-speaker-mixtures.zip脚本得到了混合后的音频文件，.scp文件是指这个压缩包里的mix_2_spk_cv/mix_2_spk_tr/mix_2_spk_tt吗。是把这三个文件改成.scp后缀即可吗

**Comment by lvyilan23** [comment]
WSJ0/si_tr_s/4/7.wav 0.76421 WSJ0/si_tr_s/1/9.wav -0.76421 类似于这种结构吗

**Comment by funcwj** [comment]
每一行是一个key value对，utt-id /path/to/audio/file 这样

**Comment by lvyilan23** [comment]
> 每一行是一个key value对，utt-id /path/to/audio/file 这样

是用create-speaker-mixtures.zip脚本处理之后，再用其他脚本切分为utterance吗？能说的详细一点吗？
ps：这个代码是你们自己写的吗，还是在论文所给源码上修改的，我没有找到论文的源码

**Comment by funcwj** [comment]
create-speaker-mixtures.zip只是用于simu数据的，拿到数据之后这些matlab的代码就没有用了。
论文没有提供代码，这是我自己写的，网上也有其他人的复现。
我习惯用.scp格式索引数据，比较方便，自己写个脚本生成就行，很简单的。

**Comment by lvyilan23** [comment]
我还是不能理解。是这个意思吗，加入有两个语音audio1和audio2，每个audio可分为10个utterance。
那么.scp的结构是这样的吗？
utt-id1 /path/to/audio/file1
utt-id2 /path/to/audio/file1
……
utt-id10 /path/to/audio/file1
utt-id1 /path/to/audio/file2
utt-id2 /path/to/audio/file2
……
utt-id10 /path/to/audio/file2

utt-id是随意设定的，设为1~10这些数字就可以吗?
我刚接触分离这块，还是不懂怎么切分utterance，您能给我发一份代码吗，或者说一下搜索关键词

**Comment by funcwj** [comment]
一个audio就是一个utt，wsj0-2mix数据里面audio的name都是唯一的，你用它做utt-id就行，比如spk1.scp，类似这样
```
050a0501_1.7783_442o030z_-1.7783	/xxx/tt/s1/050a0501_1.7783_442o030z_-1.7783.wav
050a0502_1.3461_440o030j_-1.3461	/xxx/tt/s1/050a0502_1.3461_440o030j_-1.3461.wav
```

**Comment by lvyilan23** [comment]
好的谢谢！！我有点明白了。我先试一下
