### ISSUE TITLE
I only have the timti dataset ,how to implement this code?

### ISSUE THREAD

**Issue by JayYang-Fdu** [funcwj/uPIT-for-speech-separation#3]
hello,I'm new to deep learning,I have not the wsj0 dataset,but I have the timit dataset,so what to do to implement this code...thank you for your prompt reply...

**Comment by funcwj** [comment]
hello. You can simulate 2- or 3-speaker mixtures based on the public data, egs, [Librispeech](http://www.openslr.org/12/)  and prepare the data in .scp format. For mixture creation, you can reuse the MATLAB code released by MERL if you are not familiar with the data simulation.

**Comment by Yangjie55** [comment]
呀！不好意思，我还是不明白您说的什么意思唉。。。（原来您是中国人呀，我也是哈哈哈。）
其实我不是很明白那三个txt文档是怎么生成的，然后再用matlab生成混合语音，那个是与.scp文件格式有关的嘛？

**Comment by JayYang-Fdu** [comment]
> hello. You can simulate 2- or 3-speaker mixtures based on the public data, egs, Librispeech  and prepare the data in .scp format. For mixture creation, you can reuse the MATLAB code released by MERL if you are not familiar with the data simulation.
呀！不好意思，我还是不明白您说的什么意思唉。。。（原来您是中国人呀，我也是哈哈哈。）
其实我不是很明白那三个txt文档是怎么生成的，然后再用matlab生成混合语音，那个是与.scp文件格式有关的嘛？

**Comment by funcwj** [comment]
txt和scp没关系，txt是混合前的句子地址，scp只是我自己用于管理数据的格式。你先创建好混合句子和对应的reference，之后再准备好scp就行了，两步之间没有关系
