### ISSUE TITLE
why not "Now do not support perutt training"?

### ISSUE THREAD

**Issue by aishoot** [funcwj/uPIT-for-speech-separation#6]
您好，我有个问题想请教下您：在dataset.py中
```python
 if batch_size == 1:
     raise ValueError("Now do not support perutt training")"
```
我修改为batch size有什么不妥呢？还有就是您说的“perutt training”指什么呢？

**Comment by pchao6** [comment]
> 您好，我有个问题想请教下您：在dataset.py中
> 
> ```python
>  if batch_size == 1:
>      raise ValueError("Now do not support perutt training")"
> ```
> 
> why not? Thanks.
> 我修改为batch size有什么不妥呢？还有就是您说的“perutt training”指什么呢？
