### ISSUE TITLE
why not "Now do not support perutt training"?

### ISSUE THREAD

**Issue by aishoot** [funcwj/uPIT-for-speech-separation#7]
您好，我有个问题想请教下您：在dataset.py中
```python
 if batch_size == 1:
     raise ValueError("Now do not support perutt training")"
```
why not? Thanks.
我修改为batch size有什么不妥呢？还有就是您说的“perutt training”指什么呢？

**Comment by funcwj** [comment]
perutt指的是per-utterance（逐句）训练，即batch-size = 1。这个代码实现的比较早，这些地方实现的不是太完善，后面我也没有再采用这种方式了。这个代码里面，batch-size不为1应该都可以

**Comment by aishoot** [comment]
@funcwj 我修改代码了，可以支持逐句训练。逐句训练的话是没有其他问题的对吧？

**Comment by funcwj** [comment]
主要是训起来比较慢，最终模型的性能上也会有些影响，不过我记得wsj0-2mix这批数据，似乎batch-size小一些结果反而会好。其他应该没有什么问题。

**Comment by aishoot** [comment]
@funcwj 好勒非常感谢
