### ISSUE TITLE
请问在设计loss使用的是psm，在进行测试分离时，是否用计算出的psm乘以带噪信号的幅度，然后重叠相加还原

### ISSUE THREAD

**Issue by bailiangze** [funcwj/uPIT-for-speech-separation#8]
意思是
1.psm和iam 只是在训练时目标不同，合成都是直接带噪信号幅度乘以mask，然后还原出来？
2.请问代码中实现关于irm的吗？

**Comment by funcwj** [comment]
1. 是的
2. irm和psm都有实现，改一下配置文件就行，两个逻辑很相似

**Comment by bailiangze** [comment]
我发现只有IAM，PSM。 &nbsp;IRM不是需要目标语音的幅度之和作为分母，但是代码里面使用的是带躁语音的幅度。是不是我理解错了？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jian Wu <notifications@github.com&gt;
发送时间: 2020年11月25日 21:52
收件人: funcwj/uPIT-for-speech-separation <uPIT-for-speech-separation@noreply.github.com&gt;
抄送: bailiangze <851566168@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[funcwj/uPIT-for-speech-separation] 请问在设计loss使用的是psm，在进行测试分离时，是否用计算出的psm乘以带噪信号的幅度，然后重叠相加还原 (#8)





  
是的 

irm和psm都有实现，改一下配置文件就行，两个逻辑很相似

**Comment by funcwj** [comment]
记错了……是iam，irm没有在里面

**Comment by bailiangze** [comment]
我大概意思是代码里面实现的是IAM,而不是IRM，因为在计算loss的时候，是用的带噪信号的幅度乘上mask再减去目标信号的幅度。这样的mask不是对应的IAM吗？

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jian Wu <notifications@github.com&gt;
发送时间: 2020年11月25日 21:52
收件人: funcwj/uPIT-for-speech-separation <uPIT-for-speech-separation@noreply.github.com&gt;
抄送: bailiangze <851566168@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[funcwj/uPIT-for-speech-separation] 请问在设计loss使用的是psm，在进行测试分离时，是否用计算出的psm乘以带噪信号的幅度，然后重叠相加还原 (#8)





  
是的 

irm和psm都有实现，改一下配置文件就行，两个逻辑很相似

**Comment by funcwj** [comment]
对，是iam，时间太久了我记差了

**Comment by bailiangze** [comment]
谢谢你的解答，那我现在做IRM，是不是在求loss时为目标信号幅度之和乘上mask减去目标信号的幅度。然后分离的时候用带噪信号幅度来代替目标信号之和，乘上mask还原信号？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jian Wu <notifications@github.com&gt;
发送时间: 2020年11月25日 22:53
收件人: funcwj/uPIT-for-speech-separation <uPIT-for-speech-separation@noreply.github.com&gt;
抄送: bailiangze <851566168@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[funcwj/uPIT-for-speech-separation] 请问在设计loss使用的是psm，在进行测试分离时，是否用计算出的psm乘以带噪信号的幅度，然后重叠相加还原 (#8)





 
对，是iam，时间太久了我记差了

**Comment by funcwj** [comment]
你改一下`mixture_spect`为|s1| + |s2|就行了，infer（分离）的时候逻辑不需要变化

**Comment by bailiangze** [comment]
最后想问下，大佬请问你在做这个，觉得哪里还有提升空间吗？想改进一下。大论文缺点子，不需要很有创新型。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jian Wu <notifications@github.com&gt;
发送时间: 2020年11月25日 22:53
收件人: funcwj/uPIT-for-speech-separation <uPIT-for-speech-separation@noreply.github.com&gt;
抄送: bailiangze <851566168@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[funcwj/uPIT-for-speech-separation] 请问在设计loss使用的是psm，在进行测试分离时，是否用计算出的psm乘以带噪信号的幅度，然后重叠相加还原 (#8)





 
对，是iam，时间太久了我记差了

**Comment by funcwj** [comment]
本科，硕士还是博士？

**Comment by bailiangze** [comment]
硕士



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jian Wu <notifications@github.com&gt;
发送时间: 2020年11月25日 23:04
收件人: funcwj/uPIT-for-speech-separation <uPIT-for-speech-separation@noreply.github.com&gt;
抄送: bailiangze <851566168@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[funcwj/uPIT-for-speech-separation] 请问在设计loss使用的是psm，在进行测试分离时，是否用计算出的psm乘以带噪信号的幅度，然后重叠相加还原 (#8)





 
本科，硕士还是博士？

**Comment by funcwj** [comment]
最近这些文章太多了，这个数据集基本被刷爆了，你最近几年的文章看的多吗？

**Comment by bailiangze** [comment]
看了，比较火的，就deep clustering ，还有就是uit一些提升。我们学校大论文很水的。能复现英文的改改，就行。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jian Wu <notifications@github.com&gt;
发送时间: 2020年11月25日 23:07
收件人: funcwj/uPIT-for-speech-separation <uPIT-for-speech-separation@noreply.github.com&gt;
抄送: bailiangze <851566168@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[funcwj/uPIT-for-speech-separation] 请问在设计loss使用的是psm，在进行测试分离时，是否用计算出的psm乘以带噪信号的幅度，然后重叠相加还原 (#8)





 
最近这些文章太多了，这个数据集基本被刷爆了，你最近几年的文章看的多吗？

**Comment by funcwj** [comment]
那你还是找几篇最近的文章复现一下吧...你要是看的不全，参考下面链接：
https://github.com/gemengtju/Tutorial_Separation

**Comment by bailiangze** [comment]
好的，谢谢大佬。还想问一下，这个数据集wsj0，你们都是花钱买的吗？听说几十w，老师舍得买？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jian Wu <notifications@github.com&gt;
发送时间: 2020年11月25日 23:13
收件人: funcwj/uPIT-for-speech-separation <uPIT-for-speech-separation@noreply.github.com&gt;
抄送: bailiangze <851566168@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[funcwj/uPIT-for-speech-separation] 请问在设计loss使用的是psm，在进行测试分离时，是否用计算出的psm乘以带噪信号的幅度，然后重叠相加还原 (#8)





 
那你还是找几篇最近的文章复现一下吧...你要是看的不全，参考下面链接：
 https://github.com/gemengtju/Tutorial_Separation

**Comment by funcwj** [comment]
实验室之前就有，怎么拿到的，其实我们也不清楚

**Comment by bailiangze** [comment]
敢问大佬是哪个大学的？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jian Wu <notifications@github.com&gt;
发送时间: 2020年11月25日 23:17
收件人: funcwj/uPIT-for-speech-separation <uPIT-for-speech-separation@noreply.github.com&gt;
抄送: bailiangze <851566168@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[funcwj/uPIT-for-speech-separation] 请问在设计loss使用的是psm，在进行测试分离时，是否用计算出的psm乘以带噪信号的幅度，然后重叠相加还原 (#8)





 
实验室之前就有，怎么拿到的，其实我们也不清楚

**Comment by funcwj** [comment]
西工大

**Comment by bailiangze** [comment]
厉害

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jian Wu <notifications@github.com&gt;
发送时间: 2020年11月25日 23:19
收件人: funcwj/uPIT-for-speech-separation <uPIT-for-speech-separation@noreply.github.com&gt;
抄送: bailiangze <851566168@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[funcwj/uPIT-for-speech-separation] 请问在设计loss使用的是psm，在进行测试分离时，是否用计算出的psm乘以带噪信号的幅度，然后重叠相加还原 (#8)





 
西工大

**Comment by bailiangze** [comment]
打扰了，想问下，大佬有nmf或者CASA的传统代码吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jian Wu <notifications@github.com&gt;
发送时间: 2020年11月26日 08:59
收件人: funcwj/uPIT-for-speech-separation <uPIT-for-speech-separation@noreply.github.com&gt;
抄送: bailiangze <851566168@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[funcwj/uPIT-for-speech-separation] 请问在设计loss使用的是psm，在进行测试分离时，是否用计算出的psm乘以带噪信号的幅度，然后重叠相加还原 (#8)





 
Closed #8.
