### ISSUE TITLE
Mask issue

### ISSUE THREAD

**Issue by amrithaathma** [funcwj/uPIT-for-speech-separation#9]
Is it possible to calculate a complex mask using the code, instead of calculating irm or psm?

**Comment by funcwj** [comment]
It's possible. You can try different complex-valued masks.

**Comment by amrithaathma** [comment]
Okay, thank you! I am confused about where the actual mask estimation is taking place, as I'm new to neural networks.. I went through your code and couldn't find where exactly the IRM or PSM mask is being created. Could you point me where to look for?

**Comment by funcwj** [comment]
I didn't calculate the mask labels directly in this code. It's write in another form which is implemented in [permutation_loss function](https://github.com/funcwj/uPIT-for-speech-separation/blob/4134a7af2eda0169d272303edc382249d836d4d1/trainer.py#L155).

**Comment by funcwj** [comment]
The corresponding paper is here [link](https://arxiv.org/pdf/1703.06284.pdf). See details in equal 10 and 11.

**Comment by amrithaathma** [comment]
Thank you! I went through the papers and your code once again.. and it helped me get a good insight.
